config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  default_url_options :host => "3b72b360.ngrok.io"
  root 'jobs#index'
  resources :jobs do
  	collection do
      get :autocomplete
      get :preview
      post :edit_from_json
    end
  end
  resources :admin_jobs do
    collection do
      get :autocomplete
      get :preview
      post :edit_from_json
    end
  	put :publish
  end

  resource :sitemap, only: [:show], defaults: { format: :xml }
 end

app/models/job.rb
class Job < ActiveRecord::Base
  searchkick word_start: [:title, :location, :job_type, :company_name], suggest: [:title]
  # searchkick autocomplete: ['title']
  mount_uploader :resume, ResumeUploader

  has_many :candidates

  TYPES = {
    "--Select Job Type--" => "Unspecified",
    "Long Term" => "Long Term",
    "Project" => "Project"
  }.freeze

  scope :visible, ->{ where("jobs.visible_until >= ?", Time.now).where(published: true) }
  scope :published, ->{ where(visible_until: nil, published: true) }
  scope :unpublished, ->{ where(visible_until: nil).where(published: [false, nil]) }
  scope :newest_first, ->{ order("jobs.created_at DESC") }

  before_create :generate_token

  after_save :enqueue_create_or_update_document_job
  after_destroy :enqueue_delete_document_job


  def self.separate_title_and_location(query)
    query = query.downcase
    query = query.gsub('jobs', ' ')
    query = query.gsub('job', ' ')
    query = query.gsub('  ', ' ')
    query = query.gsub(' in ', ' ')
    query = query.gsub(' at ', ' ')
    query = query.split(' ')
  end

  def self.intelligence_search(query)
    keywords = Job.separate_title_and_location(query)

    results = nil
    keywords.each do |keyword|
      result = Job.search(keyword, fields: [:title, :location, :job_type, :company_name], match: :word_start, suggest: true).records if !keyword.blank?
      if result
        suggestion_result = result.try(:suggestions)
        Rails.logger.info "=== suggestion_result: #{suggestion_result.inspect}"

        results &= result if results
        results = result unless results
      end
    end
    results
  end

  def self.filtered(type)
    if type.in?(TYPES.values)
      where(job_type: type)
    else
      where("id > 0")
    end
  end

  def self.with_admin_scope(scope)
    if scope
      public_send(scope)
    else
      newest_first
    end
  end

  def expired?
    visible_until && visible_until < Time.now
  end

  def full_title
    "#{title} at #{company_name}"
  end

  def next_visible
    @next_visible ||= self.class.visible.order("created_at ASC").where("created_at > ?", created_at).first
  end

  def prev_visible
    @prev_visible ||= self.class.visible.order("created_at DESC").where("created_at < ?", created_at).first
  end

  def to_param
    "#{id}-#{full_title.parameterize}"
  end

  def type_specified?
    job_type.present? && job_type != "Unspecified"
  end

  def self.template
    default_text = ""
    new(description: default_text.gsub('      ', ''))
  end

  def as_indexed_json(options = {})
    self.as_json(
      only: [:id, :title, :job_type, :description, :location, :published]
    )
  end

private

  def generate_token
    self.token ||= SecureRandom.hex(100)
  end

  def enqueue_create_or_update_document_job
    Delayed::Job.enqueue CreateOrUpdateSwiftypeDocumentJob.new(self.id)
  end

  def enqueue_delete_document_job
    Delayed::Job.enqueue DeleteSwiftypeDocumentJob.new(self.id)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :verify_authenticity_token
  protect_from_forgery prepend: true, with: :exception

  def index
    if params[:q].present?
      @job_title = params[:q]
      results = Job.intelligence_search(params[:q])
      if results
        @jobs = Kaminari.paginate_array(results).page(params[:page]).per(7)
      else
        @jobs = nil
      end
    else
      @job_title = nil
      @jobs = Job.filtered(params[:q]).page(params[:page]).per_page(7).newest_first
    end
  end

  def show
    @job = Job.find(params[:id])
    set_meta_tags(
      title: [@job.title, @job.company_name].compact.join(" at "),
      og: {
        type: :article,
        title: :title,
        url: job_url(@job),
        article: {
          section: "Employability",
          published_time: @job.created_at.to_s(:iso8601),
          modified_time: @job.updated_at.to_s(:iso8601),
          expiration_time: @job.visible_until.try(:to_s, :iso8601)
        }
      }
    )

    if !params[:token].present? || params[:token] == @job.token
      @candidate = Candidate.new
    end
  end

  def edit
    if params[:edit_type].present? && params[:edit_type] == "from_preview"
      @job = Job.new(string_job_params)
      if params[:commit] == "Save and Continue"
        if @job.save
          # Send email to admin.
          JobMailer.job_email(@job).deliver
          handle_success
        end
      end
    else
      @job = Job.where(id: params[:id]).first!
    end
  end

  def edit_from_json
    if params[:edit_type].present? && params[:edit_type] == "from_preview"
      @job = Job.new(string_job_params)
      if params[:commit] == "Save and Continue"
        if @job.save
          # Send email to admin.
          JobMailer.job_email(@job).deliver
          handle_success
        end
      end
    else
      @job = Job.where(id: params[:id]).first!
    end
  end

  def new
  end

  def create
    @job = Job.new(job_params)
    render action: :preview and return if params[:commit] == "Preview"
    return render text: "Success", status: :ok if params[:honey].present?
    if @job.save
      # Send email to admin.
      JobMailer.job_email(@job).deliver
      JobMailer.job_email_by_admin(@job).deliver
      handle_success
    else
      render action: :edit
    end
  end

  def update
    @job = Job.where(id: params[:id]).first!
    if @job.update_attributes(job_params)
      handle_success
    else
      render action: :edit
    end
  end

  def preview
    @job = Job.new(job_params)
    render action: :preview
  end

  def autocomplete
    jobs = Job.search(params[:q], {
      fields: ["title^5", "location^5", "job_type", "company_name^5"],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: {below: 5},
      suggest: true
    }).map do |job| { title: job.title, title_and_location: "#{job.title} in #{job.location}", location: job.location, job_type: job.job_type, company_name: job.company_name}
    end
    render json: jobs
  end

private

  def job_params
    job_params = params.require(:job).permit(
        :token, :title, :job_type, :company_name, :salary,
        :company_url, :email, :description, :how_to_apply,
        :agencies_ok, :timezone_preferences, :location,
        :resume
    )
    job_params.permit.merge!(published: params[:commit] != "Preview")
    job_params
  end

  def string_job_params
    # new_job_params = ActionController::Parameters.new(job: JSON.parse(str_job))
    job_params = ActionController::Parameters.new(job: JSON.parse(params[:job]))
                  .require(:job).permit(
                    :token, :title, :job_type, :company_name, :salary,
                    :company_url, :email, :description, :how_to_apply,
                    :agencies_ok, :timezone_preferences, :location,
                    :resume
                  )
    job_params.permit.merge!(published: params[:commit] != "Preview")
    job_params
  end

  def handle_success
    if @job.published
      redirect_to job_path(@job, token: @job.token), notice: "All done! This job will become public once our moderators approve it."
    else
      redirect_to jobs_path
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def quick_job_icon(job)
    css_class =
      case job.job_type
      when "Project"
        "mdi-action-alarm"
      when "Long Term"
        "mdi-maps-local-mall"
      else
        "mdi-file-folder"
      end
    content_tag :i, nil, class: css_class, title: "Job type: #{job.job_type}"
  end

  def select_job_type(control_type, job_type)
    control_type == job_type ? 'selected' : 'none'
  end

  def get_description_template
    description_template = ""
  end
end

app/views/jobs/_form.html.haml
.row
  .col-md-offset-1.col-md-10
    .well.bs-component.clearfix.form-newpost
      %form#new_job.new_job{"accept-charset" => "UTF-8", :action => "/jobs", :method => "post", :enctype => "multipart/form-data"}
        %input{:name => "utf8", :type => "hidden", :value => "✓"}/
        %input{:name => "authenticity_token", :type => "hidden", :value => "CvHXz8XQMOlEbhFjFUbUqDJ+4nnjrYuikFFAscyNWVzfTLcmkc03gTaoph6PH5nZtwDu7pGOvhnReNdg7qj8xQ=="}/
        %input#token{:name => "token", :type => "hidden"}/
        %fieldset
          %legend.no-sep Tell us about the job
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_title.form-control{:name => "job[title]", :placeholder => "Job Title", :required => "required", :type => "text", :value => job.title}/
            .col-md-6.form-group
              .mb-3
                = select_tag "job[job_type]",
                  options_for_select(["Contract C2C",
                                      "Full-Time",
                                      "Internship"], job.job_type),
                  selected: "Contract C2C", class: 'form-control',
                  required: "required"
          .form-group
            %label
              Description
            %textarea#job_description.form-control{:name => "job[description]", :required => "required", :rows => "15"}
              = job.description

        %fieldset
          %legend.no-sep
            Tell us about the company
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_company_name.form-control{:name => "job[company_name]", :placeholder => "Company Name", :required => "required", :type => "text", :value => job.company_name}/
            .col-md-6.form-group
              .mb-3
                %input#job_company_location.form-control{:name => "job[location]", :placeholder => "Location", :required => "required", :type => "text", :value => job.location}/
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_company_url.form-control{:name => "job[company_url]", :placeholder => "Website URL", :type => "text", :value => job.company_url}/
            .col-md-6.form-group
              .mb-3
                %input#job_email.form-control{:name => "job[email]", :placeholder => "Email", :required => "required", :type => "email", :value => job.email}/

        .row.new-jobs-save
          .col-md-6.form-group.text-center
            %input.btn.btn-success.btn-raised{:name => "commit", :type => "submit", :value => "Preview", :id => "preview"}/
          .col-md-6.form-group.text-center
            %input.btn.btn-default.btn-raised{:name => "commit", :type => "submit", :value => "Save and Continue", :id => "save-continue"}/

app/views/jobs/_form_for_candidate.html.haml
.row
  .col-md-offset-1.col-md-10
    .show_job.bs-component.clearfix.form-newpost
      %form#new_@job.new_job{"accept-charset" => "UTF-8", :action => "/candidates", :method => "post", :enctype => "multipart/form-data"}
        %input{:name => "utf8", :type => "hidden", :value => "✓"}/
        %input{:name => "authenticity_token", :type => "hidden", :value => "CvHXz8XQMOlEbhFjFUbUqDJ+4nnjrYuikFFAscyNWVzfTLcmkc03gTaoph6PH5nZtwDu7pGOvhnReNdg7qj8xQ=="}/
        %input#token{:name => "token", :type => "hidden"}/
        %input{:name => "candidate[job_id]", :type => "hidden", :value => @job.id}/
        %fieldset
          %legend.no-sep
            Tell us about yourself
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_company_name.form-control{:name => "candidate[name]", :placeholder => "Name", :required => "required", :type => "text", :value => @candidate.name}/
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_email.form-control{:name => "candidate[email]", :placeholder => "Email", :required => "required", :type => "email", :value => @candidate.email}/
          .row
            .col-md-6.form-group
              .mb-3
                %input.form-control{:name => "candidate[phone_number]", :placeholder => "Phone", :required => "required", :type => "text", :value => @candidate.phone_number}/
          .row
            .col-md-6.form-group
              %legend.no-sep
                = "Resume"
              %label
                = file_field_tag "candidate[resume]"

          .row
            .col-6.form-group.text-center
              %input.btn.btn-default.btn-raised{:name => "commit", :type => "submit", :value => "Apply", :id => "apply_button"}/

              :javascript
                $("#apply_button").on("click", function(e) {
                  var files = document.getElementById("candidate_resume").files;
                  if (files === 'undefined' || files.length === 0) {
                    e.preventDefault();
                    alert('You must upload a resume file.');
                    return;
                  } else {
                    $(".alert").fadeIn(1000);
                  }
                });

app/views/jobs/_quick_job.html.haml
%tr
  %td.description-container.col-md-10.col-sm-10.col-xs-12
    .description
      %span.home-job-title
        = link_to job.title, job
      %span.home-job-city
        |
        = job.location
      %span.home-job-company
        = link_to job.company_name, url_with_protocol(job.company_url), target: "_blank"

  %td.home-date.col-md-2.col-sm-2.hidden-xs
    %span.date
      = "#{job.updated_at.strftime('%B %e')}"

app/views/jobs/_show_job.html.haml
= render 'shared/alert_job_action', type: 'success', highlight: "#{@job.title}: ", text: "Your application has been submitted successfully"

.row.test-job-form
  .col-md-offset-1.col-md-10
    .show_jobs.bs-component.clearfix.job-box
      - text = "#{@job.company_name} is hiring a #{@job.title}"

      = link_to new_job_path, class: 'pull-right post-new-in-show-page plusBtn bigGlobalBtn' do
        %span
      = mail_to "", subject: text, body: "#{text}\n#{job_url(@job)}", class: "pull-right mail-new emailBtn smGlobalBtn" do
        %span
      = link_to "http://twitter.com/intent/tweet?url=#{job_url(@job)}&text=#{text}", target: "_blank", class: "pull-right twitter-new twitterBtn twGlobalBtn" do
        %span

      %h2.job-title
        = @job.title
      .col-md-12
        - if @job.type_specified?
          %p.job-type
            %label#jobtype
              = link_to @job.company_name, url_with_protocol(@job.company_url), target: "_blank"
              |
            %label#jobtype
              = @job.location
              |
            %label#jobtype
              = @job.job_type
              |
            %label#jobtype
              = @job.created_at.strftime('%B %e')

        %p= md @job.description

app/views/jobs/edit_from_json.html.haml
= render 'form', job: @job

app/views/jobs/index.html.haml
.row
  .col-md-offset-1.col-md-10
    .well.bs-component
      %table.table
        %tbody
          = render partial: 'quick_job', collection: @jobs, as: :job

      = link_to new_job_path, class: 'pull-right post-new plusBtn bigGlobalBtn' do
        %span

      .text-center
        - if @jobs
          = paginate @jobs

app/views/jobs/preview.html.haml
= render 'shared/alert', type: 'info', highlight: "This is a preview.", text: "The job is not visible publicly. Do not share this link, it allows editing the job posting."

.row.test-job-form
  .col-md-offset-1.col-md-10
    .show_jobs.bs-component.clearfix.job-box
      - text = "#{@job.company_name} is hiring a #{@job.title}"
      = mail_to "", subject: text, body: "#{text}\n#{job_url(@job)}", class: "pull-right mail-new emailBtn smGlobalBtn" do
        %span
      = link_to "http://twitter.com/intent/tweet?url=#{job_url(@job)}&text=#{text}", target: "_blank", class: "pull-right twitter-new twitterBtn twGlobalBtn" do
        %span

      %h2.job-title
        = @job.title
        %small
          at
          = link_to @job.company_name, url_with_protocol(@job.company_url), target: "_blank"
          in
          = @job.location
      .col-md-12
        - if @job.type_specified?
          %p.job-type
            %label#jobtype Job type -
            = quick_job_icon @job
            %span.job-type
              = @job.job_type
              |
            %label#jobtype Posted on
            = "#{Time.now.strftime('%B %e')}"

        %p= md @job.description

      - job_edit_url = edit_from_json_jobs_path
      - job_edit_method = 'post'

      %form{"accept-charset" => "UTF-8", :action => job_edit_url, :method => job_edit_method, :remote => true, :authenticity_token => true}
        %input{:name => "edit_type", :type => "hidden", :value => "from_preview"}/
        %input{:name => "job", :type => "hidden", :value => @job.to_json}/
        %input{:name => "authenticity_token", :type => "hidden", :value => "CvHXz8XQMOlEbhFjFUbUqDJ+4nnjrYuikFFAscyNWVzfTLcmkc03gTaoph6PH5nZtwDu7pGOvhnReNdg7qj8xQ=="}/
        %input#token{:name => "token", :type => "hidden"}/

        .row.new-jobs-save
          .col-md-6.form-group.text-center
            %input.btn.btn-default.btn-raised{:name => "commit", :type => "submit", :value => "Edit job", :id => "save-continue"}/

          .col-md-6.form-group.text-center
            %input.btn.btn-default.btn-raised{:name => "commit", :type => "submit", :value => "Save and Continue", :id => "save-continue"}/

app/views/jobs/show.html.haml
= render "jobs/show_job", job: @job
= render "jobs/form_for_candidate", job: @job, candidate: @candidate