config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  default_url_options :host => "3b72b360.ngrok.io"
  root 'jobs#index'
  resources :jobs do
  	collection do
      get :autocomplete
      get :preview
      post :edit_from_json
    end
  end
  resources :admin_jobs do
    collection do
      get :autocomplete
      get :preview
      post :edit_from_json
    end
  	put :publish
  end

  resource :sitemap, only: [:show], defaults: { format: :xml }
 end

app/models/candidate.rb
class Candidate < ApplicationRecord
	belongs_to :job
  mount_uploader :resume, ResumeUploader
	validates_presence_of :resume
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  def create
    @job = Job.find(params[:candidate][:job_id])
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      begin
        JobMailer.apply_email(@candidate).deliver
        JobMailer.apply_confirm_email(@candidate).deliver
        flash[:success] = "sent email successfully"
      rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError => e
        flash[:error] = "Problems sending mail. #{e.to_s}"
        Rails.logger.info "=== mail error: #{e.to_s}"
      end
      redirect_to jobs_path
    else
      flash[:error] = @job.errors.full_messages
      redirect_to job_path @job
    end
  end

  # PATCH/PUT /candidates/1
  def update
    if @candidate.update(candidate_params)
      redirect_to @candidate, notice: 'Candidate was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /candidates/1
  def destroy
    @candidate.destroy
    redirect_to candidates_url, notice: 'Candidate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def candidate_params
      params.require(:candidate).permit(:name, :phone_number, :email, :resume, :job_id)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_with(model: candidate, local: true) do |form| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :candidate_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :candidate_phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :candidate_email %>
  </div>

  <div class="field">
    <%= form.label :resume %>
    <%= form.text_field :resume, id: :candidate_resume %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Resume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.name %></td>
        <td><%= candidate.phone_number %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.resume %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @candidate.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate.email %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @candidate.resume %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>