config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  default_url_options :host => "3b72b360.ngrok.io"
  root 'jobs#index'
  resources :jobs do
  	collection do
      get :autocomplete
      get :preview
      post :edit_from_json
    end
  end
  resources :admin_jobs do
    collection do
      get :autocomplete
      get :preview
      post :edit_from_json
    end
  	put :publish
  end

  resource :sitemap, only: [:show], defaults: { format: :xml }
 end

app/controllers/admin_jobs_controller.rb
class AdminJobsController < ApplicationController
  http_basic_authenticate_with name: "superuser", password: ENV['ADMIN_PASSWORD']

  def index
    if params[:q].present?
      @job_title = params[:q]
      results = Job.intelligence_search(params[:q])
      if results && results.size > 0
        @jobs = Kaminari.paginate_array(results).page(params[:page]).per(4)
      else
        @jobs = nil
      end
    else
      @job_title = nil
      @jobs = Job.filtered(params[:q]).page(params[:page]).per_page(4).newest_first
    end
    # @jobs = Job.newest_first.with_admin_scope(params[:scope]).page(params[:page]).per_page(4)
    session[:admin] = true
    @is_admin = true
  end

  def new
  end

  def create
    if params[:id].present?
      @job = Job.find(params[:id])
      @job.title          = params[:job][:title]
      @job.job_type       = params[:job][:job_type]
      @job.description    = params[:job][:description]
      @job.company_name   = params[:job][:company_name]
      @job.location       = params[:job][:location]
      @job.company_url    = params[:job][:company_url]
      @job.email          = params[:job][:email]
    else
      @job = Job.new(job_params)
    end

    render action: :preview and return if params[:commit] == "Preview"
    return render text: "Success", status: :ok if params[:honey].present?

    if @job.save
      # Send email to admin.
      JobMailer.job_email_by_admin(@job).deliver
      handle_success
    else
      render action: :edit
    end
  end

  def update
    @job = Job.where(id: params[:id]).first
    render action: :preview and return if params[:commit] == "Preview"
    if @job.update_attributes(job_params)
      handle_success
    else
      render action: :show
    end
  end

  def publish
    job = Job.find(params[:admin_job_id])
    job.update_column(:visible_until, 1.month.from_now)
    redirect_back fallback_location: admin_jobs_path, notice: "Visible until #{job.visible_until}"
  end

  def destroy
    job = Job.find(params[:id])
    job.destroy
    redirect_to admin_jobs_path(scope: :unpublished)
  end

  def edit
    if params[:edit_type].present? && params[:edit_type] == "from_preview"
      @job = Job.new(string_job_params)
      if params[:commit] == "Save and Continue"
        if @job.save
          # Send email to admin.
          # JobMailer.job_email(@job).deliver
          handle_success
        end
      end
    else
      @job = Job.where(id: params[:id]).first!
    end
  end

  def edit_from_json
    if params[:edit_type].present? && params[:edit_type] == "from_preview"
      @job = Job.new(string_job_params)
      if params[:commit] == "Save and Continue"
        if @job.save
          # Send email to admin.
          JobMailer.job_email(@job).deliver
          handle_success
        end
      end
    else
      @job = Job.where(id: params[:id]).first!
    end
  end

  def show
    @job = Job.find(params[:id])
    set_meta_tags(
      title: [@job.title, @job.company_name].compact.join(" at "),
      og: {
        type: :article,
        title: :title,
        url: job_url(@job),
        article: {
          section: "Employability",
          published_time: @job.created_at.to_s(:iso8601),
          modified_time: @job.updated_at.to_s(:iso8601),
          expiration_time: @job.visible_until.try(:to_s, :iso8601)
        }
      }
    )
  end

  private

  def safe_find_job
    Job.where(id: params[:id], token: params[:token]).first!
  end

  def job_params
    job_params = params.require(:job).permit(
      :token, :title, :job_type, :company_name, :salary,
      :company_url, :email, :description, :how_to_apply,
      :agencies_ok, :timezone_preferences, :location,
      :resume
    )
    job_params.permit.merge!(published: params[:commit] != "Preview")
    job_params
  end

  def string_job_params
    # new_job_params = ActionController::Parameters.new(job: JSON.parse(str_job))
    job_params = ActionController::Parameters.new(job: JSON.parse(params[:job]))
                  .require(:job).permit(
                    :id, :token, :title, :job_type, :company_name, :salary,
                    :company_url, :email, :description, :how_to_apply,
                    :agencies_ok, :timezone_preferences, :location,
                    :resume
                  )
    job_params.permit.merge!(published: params[:commit] != "Preview")
    job_params
  end

  def handle_success
    if @job.published
      redirect_to admin_job_path(@job, token: @job.token), notice: "All done! This job will become public once our moderators approve it."
    else
      redirect_to admin_job_path(@job, token: @job.token)
    end
  end

end

app/views/admin_jobs/_form.html.haml
.row
  .col-md-offset-1.col-md-10
    .well.bs-component.clearfix.form-newpost
      %form#new_job.new_job{"accept-charset" => "UTF-8", :action => admin_jobs_path, :method => :post}
        %input{:name => "id", :type => "hidden", :value => job.id}
        %input{:name => "_method", :type => "hidden", :value => "post"}
        %input{:name => "utf8", :type => "hidden", :value => "✓"}/
        %input{:name => "authenticity_token", :type => "hidden", :value => "CvHXz8XQMOlEbhFjFUbUqDJ+4nnjrYuikFFAscyNWVzfTLcmkc03gTaoph6PH5nZtwDu7pGOvhnReNdg7qj8xQ=="}/
        %input#token{:name => "token", :type => "hidden"}/
        %fieldset
          %legend.no-sep Tell us about the job
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_title.form-control{:name => "job[title]", :placeholder => "Job Title", :required => "required", :type => "text", :value => job.title}/
            .col-md-6.form-group
              .mb-3
                = select_tag "job[job_type]",
                  options_for_select(["Contract C2C",
                                      "Full-Time",
                                      "Internship"], job.job_type),
                  selected: "Contract C2C", class: 'form-control',
                  required: "required"
          .form-group
            %label
              Description
            %textarea#job_description.form-control{:name => "job[description]", :required => "required", :rows => "15"}
              = job.description

        %fieldset
          %legend.no-sep
            Tell us about the company
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_company_name.form-control{:name => "job[company_name]", :placeholder => "Company Name", :required => "required", :type => "text", :value => job.company_name}/
            .col-md-6.form-group
              .mb-3
                %input#job_company_location.form-control{:name => "job[location]", :placeholder => "Location", :required => "required", :type => "text", :value => job.location}/
          .row
            .col-md-6.form-group
              .mb-3
                %input#job_company_url.form-control{:name => "job[company_url]", :placeholder => "Website URL", :type => "text", :value => job.company_url}/
            .col-md-6.form-group
              .mb-3
                %input#job_email.form-control{:name => "job[email]", :placeholder => "Email", :required => "required", :type => "email", :value => job.email}/

        .row.new-jobs-save
          .col-md-6.form-group.text-center
            %input.btn.btn-success.btn-raised{:name => "commit", :type => "submit", :value => "Preview", :id => "preview"}/
          .col-md-6.form-group.text-center
            %input.btn.btn-default.btn-raised{:name => "commit", :type => "submit", :value => "Save and Continue", :id => "save-continue"}/

app/views/admin_jobs/_quick_job.html.haml
%tr
  %td.description-container.col-md-10.col-sm-10.col-xs-12
    .description
      %span.home-job-title
        = link_to job.title, admin_job_path(job)
      %span.home-job-city
        |
        = job.location
      %span.home-job-company
        = link_to job.company_name, url_with_protocol(job.company_url), target: "_blank"
        %p
          = link_to "Edit", edit_admin_job_path(job, token: job.token)
          = link_to "Delete", admin_job_path(job, token: job.token), method: :delete, class: 'text-warning', data: { confirm: "Delete?" }
  %td.home-date.col-md-2.col-sm-2.hidden-xs
    %span.date
      = "#{job.updated_at.strftime('%B %e')}"

app/views/admin_jobs/_show_job.html.haml
.row.test-job-form
  .col-md-offset-1.col-md-10
    .well.bs-component.clearfix.job-box
      = link_to new_admin_job_path, class: 'pull-right post-new plusBtn bigGlobalBtn' do
        %span
      - text = "#{@job.company_name} is hiring a #{@job.title}"
      = mail_to "", subject: text, body: "#{text}\n#{job_url(@job)}", class: "pull-right mail-new emailBtn smGlobalBtn" do
        %span
      = link_to "http://twitter.com/intent/tweet?url=#{job_url(@job)}&text=#{text}", target: "_blank", class: "pull-right twitter-new twitterBtn twGlobalBtn" do
        %span

      %h2.job-title
        = @job.title
        %small
          at
          = link_to @job.company_name, url_with_protocol(@job.company_url), target: "_blank"
          in
          = @job.location
      .col-md-12
        - if @job.type_specified?
          %p.job-type
            %label#jobtype Job type -
            = quick_job_icon @job
            %span.job-type
              = @job.job_type
              |
            %label#jobtype Posted on
            = "#{@job.created_at.strftime('%B %e')}"

        %p= md @job.description

        - if !@job.resume.to_s.blank?
          .row.apply-job
            .pa-box
              %span.box-title
                = link_to "Download resume", @job.resume_url, class: 'btn btn-default btn-raised'

        .row.marg-20
          .text-center
            - if @job.persisted?
              = link_to "Admin Delete", admin_job_path(@job, token: @job.token), method: :delete, class: 'btn btn-raised btn-danger', data: { confirm: "Delete?" }
              = link_to "Admin Publish", admin_job_publish_path(@job, token: @job.token), method: :put, class: 'btn btn-raised btn-warning'
            = link_to "Edit the Job", edit_admin_job_path(@job, token: @job.token), class: 'btn btn-default btn-raised'
            - if !@job.published?
              = link_to "All good, make it live", admin_job_path(@job, job: {published: true}, token: @job.token), class: 'btn btn-success btn-raised', method: :patch

app/views/admin_jobs/edit.html.haml
= render 'form', job: @job

app/views/admin_jobs/edit_from_json.html.haml
= render 'form', job: @job

app/views/admin_jobs/index.html.haml
.row
  .col-md-offset-1.col-md-10
    .well.bs-component
      = link_to new_admin_job_path, class: 'pull-right post-new plusBtn bigGlobalBtn' do
        %span

      .menu.text-center.landing-lead
        = link_to "All", url_for(params.permit.merge(scope: nil))
        = link_to "Visible", url_for(params.permit.merge(scope: 'visible'))
        = link_to "Published", url_for(params.permit.merge(scope: 'published'))
        = link_to "Unpublished", url_for(params.permit.merge(scope: 'unpublished'))
      .list-group.admin-jobs
        %table.table
          %tbody
            = render partial: 'quick_job', collection: @jobs, as: :job
        .text-center
          = paginate @jobs

app/views/admin_jobs/new.html.haml
= render 'form', job: Job.template

app/views/admin_jobs/preview.html.haml
= render 'shared/alert', type: 'info', highlight: "This is a preview.", text: "The job is not visible publicly. Do not share this link, it allows editing the job posting."

.row.test-job-form
  .col-md-offset-1.col-md-10
    .show_jobs.bs-component.clearfix.job-box
      - text = "#{@job.company_name} is hiring a #{@job.title}"
      = mail_to "", subject: text, body: "#{text}\n#{job_url(@job)}", class: "pull-right mail-new emailBtn smGlobalBtn" do
        %span
      = link_to "http://twitter.com/intent/tweet?url=#{job_url(@job)}&text=#{text}&via=rails_remote", target: "_blank", class: "pull-right twitter-new twitterBtn twGlobalBtn" do
        %span

      %h2.job-title
        = @job.title
        %small
          at
          = link_to @job.company_name, url_with_protocol(@job.company_url), target: "_blank"
          in
          = @job.location
      .col-md-12
        - if @job.type_specified?
          %p.job-type
            %label#jobtype Job type -
            = quick_job_icon @job
            %span.job-type
              = @job.job_type
              |
            %label#jobtype Posted on
            = "#{Time.now.strftime('%B %e')}"

        %p= md @job.description

      - admin_job_edit_url = edit_from_json_admin_jobs_path
      - admin_job_edit_method = 'post'

      %form{"accept-charset" => "UTF-8", :action => admin_job_edit_url, :method => admin_job_edit_method, :remote => true, :authenticity_token => true}
        %input{:name => "edit_type", :type => "hidden", :value => "from_preview"}/
        %input{:name => "job", :type => "hidden", :value => @job.to_json}/
        %input{:name => "authenticity_token", :type => "hidden", :value => "CvHXz8XQMOlEbhFjFUbUqDJ+4nnjrYuikFFAscyNWVzfTLcmkc03gTaoph6PH5nZtwDu7pGOvhnReNdg7qj8xQ=="}/
        %input#token{:name => "token", :type => "hidden"}/

        .row.new-jobs-save
          .col-md-6.form-group.text-center
            %input.btn.btn-default.btn-raised{:name => "commit", :type => "submit", :value => "Edit job", :id => "save-continue"}/

          .col-md-6.form-group.text-center
            %input.btn.btn-default.btn-raised{:name => "commit", :type => "submit", :value => "Save and Continue", :id => "save-continue"}/

app/views/admin_jobs/show.html.haml
- if params[:token] == @job.token
  = render 'shared/alert', type: 'info', highlight: "This is a preview.", text: "The job is not visible publicly. Do not share this link, it allows editing the job posting."

= render "admin_jobs/show_job", job: @job